Repository Manchui/Frontend, pull requests merged in 2024-11, with the labels that each got.

#41 [Feat] library setting
  package.json
  public/lottie/check.json
  public/lottie/error.json
  src/components/main/CardSection/CardContent/index.tsx
  src/components/main/FilterSection/RegionDropdown/index.tsx
  src/components/shared/GNB/index.tsx
  src/components/shared/Toast/index.tsx
  src/data/main.json
  src/pages/_app.tsx
  src/styles/toastify-custom.css
  yarn.lock
Labels: ✨Feat, 🔥우선순위: 높음

#42 [Feat] GNB-Component
  .gitignore
  package.json
  src/apis/api.tsx
  src/apis/userApi.tsx
  src/components/Drawer/index.tsx
  src/components/shared/GNB/Toggle.tsx
  src/components/shared/GNB/index.tsx
  src/store/userStore.ts
  yarn.lock
Labels: ✨Feat, 🌟우선순위: 중간, ♻️Reactor, 🏡Setting

#43 [Feat] mypage UI
  public/icons/check-black.svg
  public/icons/check.png
  public/images/bg1-profile.png
  public/images/bg1-profile.svg
  public/images/buddah-login.png
  public/images/buddah-login.svg
  public/images/love-bookmarkpage.svg
  public/images/together-findpage-2xl.png
  public/images/together-findpage-default.png
  public/images/together-findpage.svg
  public/images/write-reviewpage.png
  public/images/write-reviewpage.svg
  src/components/mypage/dummy/Dummy.tsx
  src/components/mypage/meeting-card/index.tsx
  src/components/mypage/profile-card/index.tsx
  src/components/mypage/reviewable-card/index.tsx
  src/components/shared/RootLayout/index.tsx
  src/components/shared/button/index.tsx
  src/components/shared/chip/State.tsx
  src/data/mypage-gatherings.json
  src/pages/mypage/index.tsx
  src/styles/tailwind.screens.ts
  src/types/mypage.tsx
  src/types/type.tsx
Labels: ✨Feat, 🔥우선순위: 높음, 🎀Design

#44 [Feat] GNB-Component / Login-page / Sign-page
  .gitignore
  src/apis/api.tsx
  src/apis/userApi.tsx
  src/components/shared/GNB/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: 🚑 Bug, ✨Feat, 🔥우선순위: 높음

#46 [Feat] Main Page API 연결 및 SSR 적용(Tanstack Query + Zustand)
  .gitignore
  eslint/custom-rules.js
  next.config.mjs
  public/icons/heart-outline.svg
  public/icons/heart-red.svg
  public/icons/main/0.jpg
  public/icons/main/1.jpg
  public/icons/main/2.jpg
  public/icons/main/3.jpg
  public/icons/main/4.jpg
  public/icons/main/5.jpg
  public/icons/main/6.jpg
  public/icons/main/7.jpg
  public/icons/main/8.jpg
  public/icons/main/9.jpg
  public/icons/main/banner-btn.svg
  public/icons/main/develop.svg
  src/apis/api.tsx
  src/apis/getGatheringData.ts
  src/components/Create/CategoryDropdown/index.tsx
  src/components/Create/LocationDropdown/index.tsx
  src/components/main/CardSection/CardContent/index.tsx
  src/components/main/CardSection/CardImage/index.tsx
  src/components/main/CardSection/index.tsx
  src/components/main/Dropdown/index.tsx
  src/components/main/FilterSection/CategoryList/CategoryItems/index.tsx
  src/components/main/FilterSection/CategoryList/index.tsx
  src/components/main/FilterSection/CloseDateToggle/index.tsx
  src/components/main/FilterSection/DateDropdown/index.tsx
  src/components/main/FilterSection/RegionDropdown/index.tsx
  src/components/main/FilterSection/index.tsx
  src/components/main/HeaderSection/Header/index.tsx
  src/components/main/HeaderSection/SearchBar/index.tsx
  src/components/main/HeaderSection/index.tsx
  src/components/main/MainCarousel/index.tsx
  src/components/shared/Calendar/RenderCalendar/index.tsx
  src/components/shared/Calendar/index.tsx
  src/constants/constants.tsx
  src/constants/contants.ts
  src/constants/device.ts
  src/constants/main/contants.ts
  src/constants/server.ts
  src/hooks/useDeviceState.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useMediaQeury.ts
  src/pages/_document.tsx
  src/pages/login/index.tsx
  src/pages/main/index.tsx
  src/styles/tailwind.backgroundImage.ts
  src/styles/tailwind.typography.ts
  src/types/common.d.ts
  src/types/gathering.d.ts
  src/types/main/types.ts
  tailwind.config.ts
Labels: ✨Feat, 🔥우선순위: 높음

#51 [Feat] Bookmark Page UI 작업
  src/components/bookmark/BookmarkBanner/index.tsx
  src/components/bookmark/BookmarkCardList/index.tsx
  src/components/bookmark/BookmarkContainer/index.tsx
  src/components/bookmark/BookmarkFilter/index.tsx
  src/components/bookmark/BookmarkHeader/index.tsx
  src/components/main/CardSection/CardContent/index.tsx
  src/components/main/HeaderSection/SearchBar/index.tsx
  src/pages/bookmark/index.tsx
  src/styles/tailwind.colors.ts
  src/styles/tailwind.height.ts
  src/styles/tailwind.typography.ts
Labels: ✨Feat, 🔥우선순위: 높음, 🎀Design

#52 [Feat] Page/mypage
  src/apis/userApi.tsx
  src/components/loginLogout/Carousel/index.tsx
  src/components/mypage/profile-card/index.tsx
  src/components/shared/GNB/index.tsx
  src/libs/formatDate.ts
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/store/userStore.ts
Labels: ✨Feat, 🌟우선순위: 중간

#55 [Fix] 찜한모임 페이지 최적화 작업 및 디자인, 코드 수정
  src/apis/getGatheringData.ts
  src/components/main/CardSection/index.tsx
  src/components/main/FilterSection/CategoryList/index.tsx
  src/components/main/MainCarousel/index.tsx
  src/hooks/useGetGatheringData.ts
  src/pages/main/index.tsx
  src/styles/globals.css
  src/styles/swiper.css
  tailwind.config.ts
Labels: 🔥우선순위: 높음, ♻️Reactor

#58 [Refactor] Pagination eslint 오류 해결
  src/components/shared/pagination/index.tsx
  src/pages/bookmark/index.tsx
  src/pages/review/index.tsx
Labels: 🔥우선순위: 높음, ♻️Reactor

#59 [Bug] pagination
  src/components/shared/pagination/index.tsx
Labels: 🚑 Bug, 🔥우선순위: 높음

#60 [Refactor] Pagination eslint 오류 때문에 컴포넌트 이름 변경
  src/components/shared/PaginationBtn/Button/index.tsx
  src/components/shared/PaginationBtn/index.tsx
  src/pages/bookmark/index.tsx
  src/pages/review/index.tsx
Labels: 🔥우선순위: 높음, ♻️Reactor

#62 [Fix] 코드 최적화 및 디자인 수정
  public/lottie/404.json
  public/lottie/empty.json
  src/components/bookmark/BookmarkBanner/index.tsx
  src/components/bookmark/BookmarkCardList/index.tsx
  src/components/bookmark/BookmarkHeader/index.tsx
  src/components/main/CardSection/CardImage/index.tsx
  src/components/main/CardSection/index.tsx
  src/components/main/Dropdown/index.tsx
  src/components/main/FilterSection/CloseDateToggle/index.tsx
  src/components/main/FilterSection/DateDropdown/index.tsx
  src/components/main/FilterSection/index.tsx
  src/components/main/HeaderSection/Header/index.tsx
  src/components/main/HeaderSection/SearchBar/index.tsx
  src/components/main/MainCarousel/CarouselContent/index.tsx
  src/components/main/MainCarousel/index.tsx
  src/components/main/MainContainer/index.tsx
  src/components/shared/Calendar/index.tsx
  src/hooks/useGetBookmarkData.ts
  src/hooks/useGetGatheringData.ts
  src/pages/bookmark/index.tsx
  src/pages/main/index.tsx
  src/styles/globals.css
  src/styles/swiper.css
  src/styles/tailwind.height.ts
Labels: 🔥우선순위: 높음, ♻️Reactor

#64 [Feat] detail page
  src/components/detail/FloatingBar.tsx
  src/components/detail/GatheringCard.tsx
  src/components/detail/ReviewListCard.tsx
  src/components/detail/button/CancelButton.tsx
  src/components/detail/button/ShareButton.tsx
  src/components/detail/score/index.tsx
  src/components/shared/progress-bar/index.tsx
  src/pages/detail/[id]/index.tsx
  src/types/detail.tsx
Labels: ✨Feat, 🔥우선순위: 높음

#61 [Feat]reviewpage 정렬필터, 모임상세페이지 이동, 카드디자인 수정
  src/components/review/FilterSection/CategoryList/CategoryItems/index.tsx
  src/components/review/FilterSection/CategoryList/index.tsx
  src/components/review/FilterSection/DateDropdown/index.tsx
  src/components/review/FilterSection/RegionDropdown/index.tsx
  src/components/review/FilterSection/ReviewRating/index.tsx
  src/components/review/FilterSection/SortToggle/index.tsx
  src/components/review/FilterSection/index.tsx
  src/components/review/HeaderSection/Header/index.tsx
  src/components/review/HeaderSection/MainHeader/index.tsx
  src/components/review/HeaderSection/SearchBar/index.tsx
  src/components/review/HeaderSection/index.tsx
  src/components/review/ReviewCard/MoreButton/index.tsx
  src/components/review/ReviewCard/index.tsx
  src/components/review/ReviewCardList/index.tsx
  src/components/review/ReviewContainer/index.tsx
  src/components/review/ReviewRating/index.tsx
  src/pages/review/index.tsx
  src/types/review.d.ts
Labels: ✨Feat, 🔥우선순위: 높음, ♻️Reactor, 🎀Design

#65 Fix: 타입 수정
  src/types/mypage.tsx
Labels: 🚑 Bug, 🔥우선순위: 높음

#66 [Bug] mypage/type
  src/components/detail/button/AttendanceButton.tsx
  src/components/detail/button/CancelButton.tsx
Labels: 🚑 Bug, 🔥우선순위: 높음

#72 [Feat] MainPage 최적화 + 애니메이션 추가
  src/components/landing/FeatureSection/index.tsx
  src/components/landing/ImageSection/index.tsx
  src/components/landing/LandingMain/index.tsx
  src/components/main/CardSection/index.tsx
  src/components/main/Dropdown/index.tsx
  src/components/main/EmptyState/index.tsx
  src/components/main/FilterSection/DateDropdown/index.tsx
  src/components/main/FilterSection/index.tsx
  src/components/main/HeaderSection/Header/index.tsx
  src/components/main/HeaderSection/SearchBar/index.tsx
  src/components/main/MainCarousel/index.tsx
  src/components/shared/Calendar/index.tsx
  src/components/shared/pageLayout/index.tsx
  src/pages/404.tsx
  src/pages/main/index.tsx
  src/styles/globals.css
Labels: ✨Feat, 🔥우선순위: 높음

#71 [Fix] mypage type
  src/apis/mypage/get-mypage-attendance.tsx
  src/apis/mypage/get-mypage-gathring.tsx
  src/apis/mypage/get-mypage-reviewable.tsx
  src/apis/mypage/get-mypage-reviews.tsx
  src/components/detail/FloatingBar.tsx
  src/components/detail/button/CancelButton.tsx
  src/components/mypage/card-style/button/CancelButton.tsx
  src/components/mypage/card-style/button/ReviewButton.tsx
  src/components/mypage/card-style/index.tsx
  src/components/mypage/card-style/meeting-card/index.tsx
  src/components/mypage/card-style/reviewable-card/index.tsx
  src/components/mypage/category/CategoryList.tsx
  src/components/mypage/category/ReviewCategory.tsx
  src/components/mypage/my-review-list/index.tsx
  src/components/mypage/profile-card/index.tsx
  src/components/shared/GNB/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/types/mypage.tsx
Labels: 🌟우선순위: 중간, ♻️Reactor

#73 [Feat] Bookmark Page 최적화 + Framer Motion 적용
  src/components/bookmark/BookmarkBanner/index.tsx
  src/components/bookmark/BookmarkHeader/GatheringCount/index.tsx
  src/components/bookmark/BookmarkHeader/index.tsx
  src/components/main/FilterSection/RegionDropdown/index.tsx
  src/components/main/HeaderSection/SearchBar/index.tsx
  src/hooks/useGetBookmarkData.ts
  src/pages/bookmark/index.tsx
Labels: ✨Feat, 🔥우선순위: 높음, 🎀Design

#74 [Feat & Refactor] Mypage-Page
  src/apis/api.tsx
  src/apis/userApi.tsx
  src/components/Create/CategoryDropdown/index.tsx
  src/components/loginLogout/Carousel/index.tsx
  src/components/mypage/profile-card/index.tsx
  src/components/shared/Input/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
Labels: 🚑 Bug, ✨Feat, 🔥우선순위: 높음, ♻️Reactor, 🎀Design

#76 [Refactoring] Signup-Page
  public/buttons/edit1-profile.svg
  public/buttons/noprofile-edit.svg
  public/buttons/noprofile-gnb.svg
  public/icons/+.svg
  public/icons/alarm-finish.svg
  public/icons/alarm.svg
  public/icons/arrow-updown.svg
  public/icons/check-black.svg
  public/icons/check.svg
  public/icons/checkbox-active.svg
  public/icons/clap-round.svg
  public/icons/clap-sentence.svg
  public/icons/clap.svg
  public/icons/dalaemfit.svg
  public/icons/heart-active.svg
  public/icons/heart-inactive.svg
  public/icons/heart-outline.svg
  public/icons/heart-red.svg
  public/icons/island.svg
  public/icons/main/all.svg
  public/icons/main/curtureart.svg
  public/icons/main/develop.svg
  public/icons/main/food.svg
  public/icons/main/game.svg
  public/icons/main/health.svg
  public/icons/main/movie.svg
  public/icons/main/music.svg
  public/icons/main/study.svg
  public/icons/main/travel.svg
  public/icons/sort-white.svg
  public/icons/sort.svg
  public/icons/updown-arrow.svg
  public/icons/x-white.svg
  public/icons/x.svg
  public/images/profile.svg
  src/apis/api.tsx
  src/apis/userApi.tsx
  src/components/main/CardSection/CardContent/index.tsx
  src/libs/validateForm.ts
  src/pages/404.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: 🚑 Bug, 🌟우선순위: 중간, ♻️Reactor

#77 [Feat] SEO 최적화 컴포넌트 제작, useRouter 커스텀 훅 제작
  src/components/main/MainCarousel/index.tsx
  src/components/shared/SEO/index.tsx
  src/constants/url.ts
  src/hooks/useGetGatheringData.ts
  src/hooks/useInternalRouter.ts
  src/pages/_app.tsx
  src/pages/bookmark/index.tsx
  src/pages/main/index.tsx
  src/utils/common.ts
Labels: ✨Feat, 🔥우선순위: 높음

#78 [Refactor] detail page
  src/components/detail/FloatingBar.tsx
  src/components/detail/GatheringCard.tsx
  src/components/detail/ReviewListCard.tsx
  src/components/detail/button/AttendanceButton.tsx
  src/components/detail/button/CancelButton.tsx
  src/components/detail/loading/Loading.tsx
  src/components/detail/score/index.tsx
  src/components/main/CardSection/CardContent/index.tsx
  src/components/mypage/card-style/index.tsx
  src/components/mypage/my-review-list/index.tsx
  src/components/shared/progress-bar/DetailsStyle.tsx
  src/pages/detail/[id]/index.tsx
  src/types/detail.tsx
Labels: 🔥우선순위: 높음, ♻️Reactor

#69 [Fix] gnb 디자인 수정완료
  public/icons/arrow-right-white.svg
  public/icons/logout-gnb.png
  public/icons/mypage-gnb.png
  public/icons/person.svg
  src/components/Drawer/MenuBtn/index.tsx
  src/components/Drawer/index.tsx
  src/components/shared/GNB/Toggle.tsx
  src/components/shared/GNB/index.tsx
  src/styles/tailwind.animation.ts
  src/styles/tailwind.keyframes.ts
Labels: ♻️Reactor, 🎀Design

#79 [Feat] Introduce page(소개 페이지)제작
  public/buttons/noprofile-edit.svg
  public/buttons/noprofile-gnb.svg
  public/icons/ArrowBtn.tsx
  public/icons/DoubleArrow.tsx
  public/icons/RedHeart.tsx
  public/icons/Search.tsx
  public/icons/arrow-right.svg
  public/icons/heart-active-half-noround.svg
  public/images/position/design.svg
  public/images/position/server.svg
  public/images/position/web.svg
  public/images/profile.svg
  src/apis/getBookmarkData.ts
  src/apis/getGatheringData.ts
  src/components/bookmark/BookmarkBanner/index.tsx
  src/components/bookmark/BookmarkCardList/index.tsx
  src/components/bookmark/BookmarkHeader/index.tsx
  src/components/detail/loading/Loading.tsx
  src/components/introduce/Card/index.tsx
  src/components/landing/LandingMain/index.tsx
  src/components/landing/PopularList/index.tsx
  src/components/landing/ReviewSection/index.tsx
  src/components/main/CardSection/CardContent/index.tsx
  src/components/main/CardSection/CardImage/index.tsx
  src/components/main/CardSection/index.tsx
  src/components/main/Carousel/index.tsx
  src/components/main/FilterSection/CloseDateToggle/index.tsx
  src/components/main/FilterSection/DateDropdown/index.tsx
  src/components/main/FilterSection/RegionDropdown/index.tsx
  src/components/main/FilterSection/index.tsx
  src/components/main/MainCardSection/index.tsx
  src/components/main/MainCarousel/CarouselContent/index.tsx
  src/components/main/MainCarousel/index.tsx
  src/components/main/MainContainer/index.tsx
  src/components/shared/Loading/index.tsx
  src/components/shared/Tag/index.tsx
  src/components/shared/pageLayout/index.tsx
  src/components/shared/progress-bar/index.tsx
  src/constants/cards.ts
  src/constants/image.ts
  src/hooks/useGetBookmarkData.ts
  src/hooks/useGetGatheringData.ts
  src/hooks/useInternalRouter.ts
  src/hooks/useLoading.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/bookmark/index.tsx
  src/pages/introduce.tsx
  src/pages/main/[id]/index.tsx
  src/pages/main/index.tsx
  src/store/useFilterStore.ts
  src/styles/globals.css
  src/styles/swiper.css
  src/styles/tailwind.colors.ts
  src/styles/tailwind.typography.ts
  src/styles/toastify-custom.css
  src/types/common.d.ts
  src/types/gathering.d.ts
  src/types/store.d.ts
  tailwind.config.ts
Labels: ✨Feat, 🔥우선순위: 높음

#80 [Feat] SpeedDial 제작
  public/icons/ArrowBtn.tsx
  public/icons/DownArrow.tsx
  public/icons/Search.tsx
  public/icons/Svg.tsx
  src/components/main/SpeedDial/SpeedCreate.tsx
  src/components/main/SpeedDial/SpeedIntroduce.tsx
  src/components/main/SpeedDial/SpeedReview.tsx
  src/components/main/SpeedDial/index.tsx
  src/components/shared/Svg/index.tsx
  src/constants/speedDial.tsx
  src/hooks/useAuthBoundary.ts
  src/pages/main/index.tsx
Labels: ✨Feat, 🌟우선순위: 중간

#82 [Feat] Main Page Carousel 제작
  public/buttons/noprofile-edit.svg
  public/buttons/noprofile-gnb.svg
  public/icons/DoubleArrow.tsx
  public/icons/RedHeart.tsx
  public/icons/Search.tsx
  public/icons/alarm-finish.svg
  public/icons/alarm.svg
  public/icons/clap-round.svg
  public/icons/clap-sentence.svg
  public/icons/clap.svg
  public/icons/dalaemfit.svg
  public/icons/island.svg
  public/icons/review.svg
  public/images/develop.webp
  public/images/food.webp
  public/images/study.webp
  src/components/main/Carousel/IntroduceSlide/index.tsx
  src/components/main/Carousel/NoticeBoardSlide/index.tsx
  src/components/main/Carousel/PopularCategorySlide/index.tsx
  src/components/main/Carousel/index.tsx
  src/components/main/MainCardSection/index.tsx
  src/components/main/MainContainer/index.tsx
  src/components/shared/GNB/index.tsx
  src/components/shared/pageLayout/index.tsx
  src/hooks/useInternalRouter.ts
  src/pages/introduce.tsx
  src/pages/main/index.tsx
  src/pages/noticeboard.tsx
  src/styles/tailwind.colors.ts
Labels: ✨Feat, 🔥우선순위: 높음

#84 [Feat] NoticeBoard Page(공지사항 페이지) 제작 (+ 무한 스크롤)
  src/components/bookmark/BookmarkHeader/GatheringCount/index.tsx
  src/components/landing/QNA/QNAItem.tsx
  src/components/landing/QNA/index.tsx
  src/components/main/Carousel/NoticeBoardSlide/index.tsx
  src/components/main/Carousel/PopularCategorySlide/index.tsx
  src/components/main/Carousel/index.tsx
  src/components/mypage/category/CategoryList.tsx
  src/components/noticeboard/NoticeBoardItem.tsx
  src/constants/noticeBoard.ts
  src/constants/qna.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/introduce.tsx
  src/pages/noticeboard.tsx
Labels: ✨Feat, 🔥우선순위: 높음

#86 [Fix]dropdown 수정
  src/components/shared/Dropdown/index.tsx
Labels: 🚑 Bug, 🔥우선순위: 높음

#87 [Feat] FAQ Carousel 슬라이드, FAQ 페이지 제작 (구글 폼 추가)
  public/images/popular.webp
  public/images/position/server.svg
  public/images/top.webp
  src/components/bookmark/BookmarkCardList/index.tsx
  src/components/introduce/Card/index.tsx
  src/components/landing/FAQ/FAQItem.tsx
  src/components/landing/FAQ/index.tsx
  src/components/main/Carousel/FAQSlide/index.tsx
  src/components/main/Carousel/IntroduceSlide/index.tsx
  src/components/main/Carousel/NoticeBoardSlide/index.tsx
  src/components/main/Carousel/PopularCategorySlide/index.tsx
  src/components/main/Carousel/TopSlide/index.tsx
  src/components/main/Carousel/index.tsx
  src/components/main/MainCardSection/index.tsx
  src/components/noticeboard/NoticeBoardItem.tsx
  src/components/shared/pageLayout/index.tsx
  src/constants/faq.ts
  src/constants/noticeBoard.ts
  src/hooks/useInternalRouter.ts
  src/pages/faq.tsx
  src/pages/index.tsx
  src/pages/noticeboard.tsx
Labels: ✨Feat, 🔥우선순위: 높음

#83 [Design] detail page
  src/components/detail/GatheringCard.tsx
  src/components/detail/ReviewListCard.tsx
  src/components/detail/button/AttendanceButton.tsx
  src/components/detail/button/CancelButton.tsx
  src/components/detail/score/index.tsx
  src/components/shared/progress-bar/DetailsStyle.tsx
  src/components/shared/progress-bar/index.tsx
  src/components/shared/tooltip/index.tsx
  src/hooks/useHeartChange.ts
  src/pages/detail/[id]/index.tsx
  src/types/detail.tsx
Labels: 🔥우선순위: 높음, 🎀Design

#85 [Refactor] Api
  package.json
  src/apis/api.tsx
  src/apis/detail/delete-cancel.tsx
  src/apis/detail/get-gathering-data.tsx
  src/apis/detail/post-attendance.tsx
  src/apis/getBookmarkData.ts
  src/apis/getGatheringData.ts
  src/apis/getReviewData.ts
  src/apis/mypage/get-mypage-attendance.tsx
  src/apis/mypage/get-mypage-gathring.tsx
  src/apis/mypage/get-mypage-reviewable.tsx
  src/apis/mypage/get-mypage-reviews.tsx
  src/apis/mypage/post-reviews.tsx
  src/apis/user/getUser.tsx
  src/apis/user/postUser.tsx
  src/apis/user/putUser.tsx
  src/apis/userApi.tsx
  src/components/Drawer/index.tsx
  src/components/loginLogout/LoginForm/index.tsx
  src/components/loginLogout/SignupForm/index.tsx
  src/components/main/CardSection/CardContent/index.tsx
  src/components/mypage/profile-card/index.tsx
  src/components/shared/GNB/Toggle.tsx
  src/components/shared/GNB/index.tsx
  src/libs/validateForm.ts
  src/pages/create/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/store/userStore.ts
  src/types/user.tsx
  yarn.lock
Labels: 🚑 Bug, 🔥우선순위: 높음, ♻️Reactor

#90 [Feat] detail page components
  public/images/img-detail-page.png
  src/components/detail/GatheringCard.tsx
  src/components/shared/kakao-map/index.tsx
  src/constants/coordinates.ts
Labels: ✨Feat, 🌟우선순위: 중간

#94 [Bug] 로그인 후 회원정보 처리
  src/apis/user/getUser.tsx
  src/apis/user/postUser.tsx
  src/components/shared/GNB/index.tsx
  src/pages/login/index.tsx
  src/pages/oauth/index.tsx
  src/store/userStore.ts
Labels: 🚑 Bug, 🔥우선순위: 높음, ♻️Reactor

#93 [Refator] detail semantics
  src/apis/detail/get-gathering-data.tsx
  src/components/detail/FloatingBar.tsx
  src/components/detail/GatheringCard.tsx
  src/components/detail/ReviewListCard.tsx
  src/components/detail/score/index.tsx
  src/components/shared/chip/DateChip.tsx
  src/components/shared/progress-bar/DetailsStyle.tsx
  src/components/shared/progress-bar/index.tsx
  src/pages/detail/[id]/index.tsx
  src/styles/tailwind.boxShadow.ts
  tailwind.config.ts
Labels: 🌟우선순위: 중간, ♻️Reactor

#95 [Refator] 마이페이지 리팩토링
  src/components/mypage/card-style/button/CancelButton.tsx
  src/components/mypage/card-style/button/ReviewButton.tsx
  src/components/mypage/card-style/index.tsx
  src/components/mypage/card-style/meeting-card/index.tsx
  src/components/mypage/card-style/reviewable-card/index.tsx
  src/components/mypage/category/CategoryList.tsx
  src/components/mypage/category/ReviewCategory.tsx
  src/components/mypage/my-review-list/index.tsx
  src/components/mypage/profile-card/index.tsx
  src/pages/mypage/index.tsx
Labels: 🌟우선순위: 중간, ♻️Reactor

#96 [Refactor] 소셜 로그인
  src/apis/user/getUser.tsx
  src/pages/oauth/index.tsx
Labels: 🔥우선순위: 높음, ♻️Reactor

#97 [Feat] 실시간 알림기능 구현 (SSE)
  package.json
  public/icons/NotificationIcon.tsx
  public/icons/XIcon.tsx
  src/apis/deleteNotificationData.ts
  src/apis/getNotificationData.ts
  src/components/Drawer/index.tsx
  src/components/main/CardSection/CardImage/index.tsx
  src/components/main/Carousel/PopularCategorySlide/index.tsx
  src/components/shared/GNB/Notification/MobileUI/index.tsx
  src/components/shared/GNB/Notification/NotificationItem/MobileUI/index.tsx
  src/components/shared/GNB/Notification/NotificationItem/TabletPCUI/index.tsx
  src/components/shared/GNB/Notification/NotificationItem/index.tsx
  src/components/shared/GNB/Notification/TabletPCUI/index.tsx
  src/components/shared/GNB/Notification/index.tsx
  src/components/shared/GNB/index.tsx
  src/hooks/useGetNotificationData.ts
  src/hooks/useNotificationDrag.ts
  src/styles/tailwind.animation.ts
  src/styles/tailwind.colors.ts
  src/styles/tailwind.keyframes.ts
  src/types/common.d.ts
  src/types/gathering.d.ts
  src/utils/dateUtils.ts
  yarn.lock
Labels: ✨Feat, 🔥우선순위: 높음

#98 [Fix] 타입 오류 해결
  src/apis/detail/post-attendance.tsx
  yarn.lock
Labels: 🚑 Bug, 🔥우선순위: 높음

#99 [Bug] 소셜로그인
  src/components/loginSignup/LoginForm/index.tsx
  src/components/shared/GNB/index.tsx
  src/pages/oauth/index.tsx
Labels: 🚑 Bug, 🔥우선순위: 높음

#100 [Fix] 디자인 수정, 코드 수정
  package.json
  public/buttons/noprofile-edit.svg
  public/buttons/noprofile-gnb.svg
  public/icons/Search.tsx
  public/icons/alarm-finish.svg
  public/icons/alarm.svg
  public/icons/clap-round.svg
  public/icons/clap-sentence.svg
  public/icons/clap.svg
  public/icons/dalaemfit.svg
  public/icons/island.svg
  public/icons/review.svg
  public/logo/google.svg
  src/components/main/Carousel/IntroduceSlide/index.tsx
  src/components/main/Carousel/NoticeBoardSlide/index.tsx
  src/components/main/Carousel/PopularCategorySlide/index.tsx
  src/components/main/Carousel/index.tsx
  src/components/main/FilterSection/index.tsx
  src/components/main/HeaderSection/Header/index.tsx
  src/components/main/HeaderSection/SearchBar/index.tsx
  src/components/main/MainCardSection/index.tsx
  src/components/shared/GNB/Notification/NotificationItem/TabletPCUI/index.tsx
  src/components/shared/GNB/Notification/index.tsx
  src/constants/cards.ts
  src/constants/pageSize.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/_app.tsx
  src/pages/bookmark/index.tsx
  src/pages/introduce.tsx
  src/pages/main/index.tsx
  src/pages/noticeboard.tsx
  src/styles/globals.css
  src/styles/tailwind.colors.ts
  src/utils/common.ts
  tailwind.config.ts
  yarn.lock
Labels: 🐢우선순위: 낮음, ♻️Reactor

#101 [refactor] gnb 프로필 화질 조정, 이동경로 수정
  src/components/Drawer/index.tsx
  src/components/shared/GNB/Notification/MobileUI/index.tsx
  src/components/shared/GNB/Toggle.tsx
  src/components/shared/GNB/index.tsx
Labels: 🌟우선순위: 중간, ♻️Reactor

#103 [refactor]생성페이지 후 경로 이동
  src/components/Create/DescriptionInput/index.tsx
  src/pages/create/index.tsx
Labels: 🔥우선순위: 높음, ♻️Reactor
