Repository Manchui/Frontend, pull requests merged in 2024-10, with the labels that each got.

#1 test PR
  src/pages/index.tsx
Labels: 우선순위: 낮음

#5 Eslint add
  .eslintrc.json
  .prettierrc
  .prettierrc.js
  .vscode/settings.json
  prettier/base.js
  prettier/tailwindcss.js
  src/pages/index.tsx
Labels: 우선순위: 높음

#6 Eslint add
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 우선순위: 높음

#11 [#9] setting files
  .github/ISSUE_TEMPLATE/♻️-reactor.md
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/🎀-design.md
  .github/ISSUE_TEMPLATE/🏡-setting.md
  .github/ISSUE_TEMPLATE/🚑-bug-.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/pages/index.tsx
Labels: 🌟우선순위: 중간, 🏡Setting

#13 Add new images
  public/buttons/edit1-profile-default.png
  public/buttons/edit1-profile-large.png
  public/buttons/edit1-profile.svg
  public/buttons/edit2-profile-default.png
  public/buttons/edit2-profile-large.png
  public/buttons/noprofile-edit.png
  public/buttons/noprofile-edit.svg
  public/buttons/noprofile-gnb-default.png
  public/buttons/noprofile-gnb-large.png
  public/buttons/noprofile-gnb-small.png
  public/buttons/noprofile-gnb.svg
  public/icons/arrow-updown.svg
  public/icons/check.png
  public/icons/check.svg
  public/icons/checkbox-active.svg
  public/icons/checkbox-inactive.svg
  public/icons/clap-round.svg
  public/icons/clap-sentence.svg
  public/icons/clap.svg
  public/icons/dalaemfit.png
  public/icons/dalaemfit.svg
  public/icons/down-white.svg
  public/icons/down.svg
  public/icons/heart-active-noround.svg
  public/icons/heart-active.svg
  public/icons/heart-inactive-noround.svg
  public/icons/heart-inactive.svg
  public/icons/island.png
  public/icons/island.svg
  public/icons/left.svg
  public/icons/person.png
  public/icons/person@2x.svg
  public/icons/right.svg
  public/icons/up.svg
  public/icons/updown-arrow-white.svg
  public/icons/visibility-off.svg
  public/icons/visibility-on.svg
  public/icons/x.svg
  public/images/bg1-profile.png
  public/images/bg1-profile.svg
  public/images/buddah-login.png
  public/images/buddah-login.svg
  public/images/love-bookmarkpage.png
  public/images/love-bookmarkpage.svg
  public/images/together-findpage-2xl.png
  public/images/together-findpage-default.png
  public/images/together-findpage-large.png
  public/images/together-findpage.svg
  public/images/write-reviewpage.png
  public/images/write-reviewpage.svg
  public/logo/logo.png
  src/_components/hi.tsx
Labels: ✨Feat

#14 [Setting] setting folder
  src/_components/hi.tsx
  src/apis/api.tsx
  src/components/mypage/dummy/Dummy.tsx
  src/components/shared/dummy/Dummy.tsx
  src/constants/constants.tsx
  src/hooks/useHook.tsx
  src/libs/libs.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/bookmark/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/main/[id]/index.tsx
  src/pages/main/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/types/type.tsx
  src/utils/utils.tsx
Labels: 🏡Setting

#15 [setting] tailwind.config 분리, eslint 오류해결, 라이브러리 설치
  .eslintrc.js
  eslint/tailwindcss.js
  eslint/typescript.js
  package.json
  src/pages/index.tsx
  src/styles/globals.css
  src/styles/tailwind.colors.ts
  src/styles/tailwind.screens.ts
  src/styles/tailwind.typography.ts
  src/utils/classNames.ts
  tailwind.config.ts
  yarn.lock
Labels: 🏡Setting

#16 [Feat] Add Reusable Input Component
  src/components/shared/Input.tsx
  src/pages/index.tsx
  yarn.lock
Labels: ✨Feat, 🌟우선순위: 중간

#18 [Feat] Modal 컴포넌트 제작
  eslint/tailwindcss.js
  src/components/shared/Modal/index.tsx
  src/hooks/useModal.tsx
  src/pages/main/index.tsx
  src/styles/tailwind.animation.ts
  src/styles/tailwind.keyframes.ts
  src/styles/tailwind.typography.ts
  tailwind.config.ts
Labels: ✨Feat

#19 [Feat] Stoybook ibrary add
  .eslintrc.js
  .github/ISSUE_TEMPLATE/♻️-reactor.md
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/🎀-design.md
  .github/ISSUE_TEMPLATE/🏡-setting.md
  .github/ISSUE_TEMPLATE/🚑-bug-.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/storybook.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/settings.json
  package.json
  src/components/shared/button/Button.stories.tsx
  src/components/shared/button/Button.tsx
  src/components/shared/dummy/Dummy.tsx
  src/stories/Configure.mdx
  tailwind.config.ts
  yarn.lock
Labels: ✨Feat, 🔥우선순위: 높음, 🏡Setting

#20 [Feat] Add Chip Components
  public/icons/check.svg
  public/icons/running-selected.png
  src/components/shared/chip/DateChip.tsx
  src/components/shared/chip/OptionButton.tsx
  src/components/shared/chip/State.tsx
Labels: ✨Feat

#21 [Feat] Husky library add
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  eslint/custom-rules.js
  eslint/typescript.js
  package.json
  src/components/shared/Input.tsx
  src/components/shared/Modal/index.tsx
  src/components/shared/button/index.stories.tsx
  src/components/shared/button/index.tsx
  src/components/shared/chip/DateChip.tsx
  src/components/shared/chip/OptionButton.tsx
  src/components/shared/chip/State.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 🔥우선순위: 높음, 🏡Setting

#17 [Feat] Add Reusable tag component
  public/icons/alarm-finish.svg
  public/icons/alarm.svg
  src/components/shared/Tag/index.tsx
Labels: ✨Feat, 🌟우선순위: 중간

#28 [Feat] Modal 버튼 추가 및 애니메이션 적용
  src/components/shared/Modal/index.stories.tsx
  src/components/shared/Modal/index.tsx
  src/pages/main/index.tsx
Labels: ✨Feat, 🔥우선순위: 높음

#29 [Feat] RootLayout 제작
  eslint/import.js
  src/components/shared/RootLayout/index.tsx
  src/components/shared/Tag/index.tsx
  src/pages/main/index.tsx
  src/styles/tailwind.colors.ts
  src/styles/tailwind.screens.ts
Labels: ✨Feat, 🔥우선순위: 높음

#22 [Feat] Calendar 제작
  public/icons/down-arrow.svg
  public/icons/left.svg
  public/icons/right.svg
  src/components/shared/Calendar/RenderCalendar/index.tsx
  src/components/shared/Calendar/index.tsx
  src/styles/tailwind.animation.ts
  src/styles/tailwind.keyframes.ts
Labels: ✨Feat, 🔥우선순위: 높음

#27 [Feat] Signup Page
  package.json
  public/images/children-signup.png
  src/components/shared/Input/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  yarn.lock
Labels: ✨Feat

#24 [Feat] progress bar
  .storybook/preview.ts
  eslint/custom-rules.js
  public/icons/check.svg
  public/icons/person-black.svg
  public/icons/person-gray.svg
  src/components/shared/Tag/index.tsx
  src/components/shared/progress-bar/BasicsStyle.tsx
  src/components/shared/progress-bar/DetailsStyle.tsx
  src/components/shared/progress-bar/index.stories.tsx
  src/components/shared/progress-bar/index.tsx
Labels: ✨Feat, 🌟우선순위: 중간

#23 [Feat] gnb 제작
  public/icons/arrow-right.svg
  public/icons/menu.svg
  public/icons/x.svg
  public/images/profile.svg
  public/logo/logo.png
  src/components/Drawer/index.tsx
  src/components/shared/GNB/index.tsx
  src/pages/main/index.tsx
Labels: ✨Feat

#25 [Feat] rating 컴포넌트 제작
  public/icons/heart-active-noround.svg
  src/components/shared/Rating/index.tsx
Labels: ✨Feat

#31 [Fix] Calendar 부모 컴포넌트한테 날짜 값 보내게 수정
  src/components/shared/Calendar/index.tsx
  src/components/shared/RootLayout/index.tsx
  src/pages/_app.tsx
  src/pages/main/index.tsx
Labels: ♻️Reactor

#32 [Fix] rating 컴포넌트 수정
  public/icons/heart-active-half-noround.svg
  src/components/shared/Rating/index.tsx
  src/pages/main/index.tsx
Labels: 🌟우선순위: 중간, ♻️Reactor

#37 [Feat] new folder for mock data
  src/data/login.json
Labels: ✨Feat, 🔥우선순위: 높음

#36 [Feat] dropdown 기능 제작
  public/icons/updown-arrow-white.svg
  public/icons/updown-arrow.svg
  src/components/shared/Dropdown/index.tsx
  src/pages/review/index.tsx
Labels: ✨Feat, 🌟우선순위: 중간

#38 [Setting] Json server
  .github/workflows/storybook.yml
  package.json
  yarn.lock
Labels: 🔥우선순위: 높음, 🏡Setting

#35 [Update] 2차 Login page와 Signup page
  public/images/board-signuppage.png
  public/images/children-signup.png
  public/images/gameday-signuppage.png
  public/images/people-signuppage.png
  public/images/test-detail.png
  src/apis/api.tsx
  src/components/Carousel/index.tsx
  src/components/shared/GNB/index.tsx
  src/components/shared/Input/index.tsx
  src/pages/detail/[id]/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: ✨Feat, 🌟우선순위: 중간, ♻️Reactor, 🎀Design

#39 [Feat] Detail Page
  public/images/img-detail-page.png
  src/apis/api.tsx
  src/apis/detail/get-gathering-data.tsx
  src/components/detail/FloatingBar.tsx
  src/components/detail/GatheringCard.tsx
  src/components/detail/ReviewListCard.tsx
  src/components/shared/Rating/index.tsx
  src/components/shared/RootLayout/index.tsx
  src/components/shared/Tag/index.stories.tsx
  src/components/shared/Tag/index.tsx
  src/components/shared/button/index.tsx
  src/components/shared/progress-bar/index.stories.tsx
  src/components/shared/progress-bar/index.tsx
  src/data/detail.json
  src/pages/detail/[id]/index.tsx
  src/pages/main/index.tsx
  src/types/detail.tsx
Labels: ✨Feat, 🌟우선순위: 중간, 🎀Design

#40 [Feat] GNB-component
  public/icons/logout-gnb.png
  public/icons/mypage-gnb.png
  public/icons/person-rounded.png
  src/apis/userApi.tsx
  src/components/Drawer/index.tsx
  src/components/shared/GNB/Toggle.tsx
  src/components/shared/GNB/index.tsx
  src/data/logout.json
  src/data/user.json
  src/pages/_app.tsx
  src/styles/tailwind.animation.ts
  src/styles/tailwind.keyframes.ts
Labels: ✨Feat, 🌟우선순위: 중간
